name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
      
    - name: Setup Android SDK
      uses: amyu/setup-android@v2
      with:
        sdk-version: '33'
        build-tools-version: '34.0.1'

    - run: ./gradlew build --stacktrace
